//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInternet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BoVoyagesADMREntities : DbContext
    {
        public BoVoyagesADMREntities()
            : base("name=BoVoyagesADMREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgencesVoyages> AgencesVoyages { get; set; }
        public virtual DbSet<Assurances> Assurances { get; set; }
        public virtual DbSet<Autorisations> Autorisations { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Commerciaux> Commerciaux { get; set; }
        public virtual DbSet<Destinations> Destinations { get; set; }
        public virtual DbSet<Dossiers> Dossiers { get; set; }
        public virtual DbSet<Personnes> Personnes { get; set; }
        public virtual DbSet<Voyages> Voyages { get; set; }
        public virtual DbSet<viewStatus> viewStatus { get; set; }
    
        public virtual int reserverVoyage(Nullable<int> idvoyage, Nullable<int> places)
        {
            var idvoyageParameter = idvoyage.HasValue ?
                new ObjectParameter("idvoyage", idvoyage) :
                new ObjectParameter("idvoyage", typeof(int));
    
            var placesParameter = places.HasValue ?
                new ObjectParameter("places", places) :
                new ObjectParameter("places", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("reserverVoyage", idvoyageParameter, placesParameter);
        }
    }
}
