//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInternet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewStatus
    {
        public int dossierId { get; set; }
        public string etat { get; set; }
        public string raisonAnnulation { get; set; }
        public int clientId { get; set; }
        public string email { get; set; }
    }
}
