//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInternet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voyages()
        {
            this.Dossiers = new HashSet<Dossiers>();
        }
    
        public int id { get; set; }
        public System.DateTime dateAller { get; set; }
        public System.DateTime dateRetour { get; set; }
        public int placesDisponibles { get; set; }
        public decimal tarifToutCompris { get; set; }
        public int destinationsId { get; set; }
        public int agencesVoyagesId { get; set; }
    
        public virtual AgencesVoyages AgencesVoyages { get; set; }
        public virtual Destinations Destinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dossiers> Dossiers { get; set; }
    }
}
